# Generated by Django 2.2.6 on 2019-11-04 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdClient', models.TextField()),
                ('Nom', models.CharField(max_length=200)),
                ('Prenom', models.CharField(max_length=200)),
                ('Credit', models.IntegerField(default=0)),
                ('Paiement', models.IntegerField(default=0)),
                ('Date_paiement', models.DateField(default=datetime.date.today)),
                ('NbRefus', models.IntegerField(default=0)),
                ('Arembourser', models.IntegerField(default=0)),
                ('Compte', models.CharField(default='', max_length=10)),
                ('Age', models.IntegerField(default=-1)),
                ('Sexe', models.CharField(max_length=5)),
                ('Email', models.CharField(max_length=200)),
                ('carteFid', models.TextField()),
                ('Phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Article')),
            ],
        ),
    ]
