# Generated by Django 3.0.1 on 2020-02-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='CustomerPromo',
        ),
        migrations.AddField(
            model_name='purchasedarticle',
            name='CustomerPromo',
            field=models.IntegerField(default=0),
        ),
    ]
