# Generated by Django 2.2.3 on 2019-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fidelityPoint',
            field=models.IntegerField(default=0),
        ),
    ]
