# Generated by Django 2.2.6 on 2019-11-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Montant',
            field=models.IntegerField(default=0),
        ),
    ]
