# Generated by Django 2.2.7 on 2019-11-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_customer_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Arembourser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Paiement',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='carteFid',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Date_paiement',
            field=models.DateField(),
        ),
    ]
