# Generated by Django 3.0.1 on 2020-02-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20200204_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedarticle',
            old_name='CustomerPromo',
            new_name='promo_client_produit',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='GlobalPromo',
            new_name='Promo_client',
        ),
    ]
