# Generated by Django 2.2.5 on 2019-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_customer_fidelitypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Account',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='Payment',
            field=models.IntegerField(default=0),
        ),
    ]
