# Generated by Django 2.2.7 on 2019-11-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_auto_20191106_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_ticket', models.DateField()),
                ('prix', models.IntegerField(default=0)),
                ('client', models.TextField()),
                ('Points_fidelite', models.IntegerField(default=0)),
                ('Mode_paiement', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeProduit', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField(default=0)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_articles', to='djangoapp.Ticket')),
            ],
        ),
    ]
