# Generated by Django 2.2.7 on 2019-11-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_purchasedarticle_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='client',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='prix',
            new_name='Prix',
        ),
        migrations.AddField(
            model_name='purchasedarticle',
            name='PrixAprès',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasedarticle',
            name='PrixAvant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasedarticle',
            name='Promo',
            field=models.IntegerField(default=0),
        ),
    ]
