# Generated by Django 2.2.7 on 2019-11-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20191124_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Prix',
            new_name='prix',
        ),
    ]
