# Generated by Django 2.2.7 on 2019-11-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_auto_20191124_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='client',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Date_ticket',
            new_name='DateTicket',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Mode_paiement',
            new_name='ModePaiement',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Points_fidelite',
            new_name='PointsFidelite',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='prix',
            new_name='Prix',
        ),
    ]
