# Generated by Django 2.2.6 on 2019-10-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_customer_cartefid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Credit',
            field=models.IntegerField(default=0),
        ),
    ]
