# Generated by Django 2.2.6 on 2019-10-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_auto_20191023_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='customer',
            name='Arembourser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='NbRefus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Sexe',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
