# Generated by Django 2.2.6 on 2019-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_auto_20191030_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
