# Generated by Django 2.2.7 on 2019-11-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0008_auto_20191124_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Date_paiement',
            field=models.DateField(null=True),
        ),
    ]
