# Generated by Django 2.2.7 on 2019-11-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_auto_20191124_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='DateTicket',
            field=models.DateField(blank=True, null=True),
        ),
    ]
