# Generated by Django 2.2.6 on 2019-11-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Phone',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='carteFid',
            field=models.TextField(),
        ),
    ]
