# Generated by Django 2.2.7 on 2019-11-24 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_auto_20191124_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedarticle',
            old_name='PrixAprès',
            new_name='PrixApres',
        ),
    ]
