# Generated by Django 2.2.7 on 2019-11-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0011_auto_20191124_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedarticle',
            old_name='CodeProduit',
            new_name='codeProduit',
        ),
        migrations.RenameField(
            model_name='purchasedarticle',
            old_name='PrixApres',
            new_name='prixApres',
        ),
        migrations.RenameField(
            model_name='purchasedarticle',
            old_name='PrixAvant',
            new_name='prixAvant',
        ),
        migrations.RenameField(
            model_name='purchasedarticle',
            old_name='Promo',
            new_name='promo',
        ),
        migrations.RenameField(
            model_name='purchasedarticle',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
