# Generated by Django 3.0 on 2019-12-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_auto_20191124_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Sexe',
            field=models.CharField(default='', max_length=5),
        ),
    ]
