# Generated by Django 3.0.1 on 2020-01-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0015_auto_20200115_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='CustomerPromo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='GlobalPromo',
            field=models.IntegerField(default=0),
        ),
    ]
