# Generated by Django 3.0.1 on 2020-02-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0016_auto_20200117_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='uid',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
